authvar: allow specifying the token name.
Chris Packham noticed that with GCC 15, when building authvar with
`-flto`, it produced the following compiler warning/error:

  authvar.c: In function 'main':
  authvar.c:450:17: error: 'free' called on a pointer to an unallocated object '"NSS Certificate DB"' [-Werror=free-nonheap-object]
    450 |                 free(tokenname);
        |                 ^
  authvar.c:270:15: note: assigned here
    270 |         char *tokenname = "NSS Certificate DB";
        |               ^
  lto1: all warnings being treated as errors
  lto-wrapper: fatal error: gcc returned 1 exit status

This is happening because the entry in the poptOptions array for setting
the token is missing, and therefore we never use the code to set
anything other than the original, so this allocation never happens.

This adds that stanza.  Thanks to Chris for noticing.

Signed-off-by: Peter Jones <pjones@redhat.com>